package org.kompiro.jamcircle.kanban.ui;

public enum KanbanImageConstants {

	OPEN_LIST_ACTION_IMAGE,
	TRASH_FULL_IMAGE,
	TRASH_EMPTY_IMAGE,
	SEND_OFF_IMAGE,SEND_ON_IMAGE,
	BACKGROUND_IMAGE,
	CONNECT_IMAGE,
	DISCONNECT_IMAGE,
	FILE_LINK_IMAGE,
	FILE_GO_IMAGE,
	LANE_ICONIZE_IMAGE,
	LANE_RESTORE_IMAGE,
	USER_IMAGE,
	COLOR_IMAGE,
	ADD_IMAGE,
	EDIT_IMAGE, 
	KANBANS_IMAGE,
	PAGE_IMAGE,
	COMPLETED_IMAGE,
	INBOX_IMAGE, 
	CAMERA_IMAGE,
	SAVE_IMAGE,
	CLOCK_IMAGE,
	CLOCK_RED_IMAGE,
	DELETE_IMAGE,
	OPEN_IMAGE,
	MOCK_IMAGE
}
